"""empty message

Revision ID: 87649ab2660b
Revises: 
Create Date: 2023-11-19 00:20:17.617586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87649ab2660b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longitud', sa.VARCHAR(length=20), nullable=False),
    sa.Column('latitud', sa.VARCHAR(length=30), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=120), nullable=False),
    sa.Column('sector', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=15), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('placa', sa.VARCHAR(length=10), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('año', sa.DATE(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('tipo_unidad', sa.VARCHAR(length=50), nullable=False),
    sa.Column('chofer', sa.VARCHAR(length=120), nullable=True),
    sa.Column('policia', sa.VARCHAR(length=120), nullable=True),
    sa.Column('operador', sa.VARCHAR(length=120), nullable=True),
    sa.Column('agentes', sa.VARCHAR(length=120), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=150), nullable=False),
    sa.Column('nacimiento', sa.DATE(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=9), nullable=False),
    sa.Column('clave', sa.VARCHAR(length=255), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=9), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denuncias')
    op.drop_table('usuarios')
    op.drop_table('unidades')
    op.drop_table('zonas')
    op.drop_table('vehiculos')
    op.drop_table('roles')
    op.drop_table('noticias')
    op.drop_table('alertas')
    # ### end Alembic commands ###
